#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################
 
# source files in this project (main.cpp is automatically assumed)
SOURCES := UART.cpp test.asm

# header files in this project
HEADERS := UART.h waitable.h 

# other places to look for files for this project
SEARCH  := UART

CLEAN += .vscode
CLEAN += __pycache__

RELATIVE	      ?= ../
include           $(RELATIVE)Makefile.inc
